---   # these --- sign indicates that it is a .yml file
name: Checks    

on: [push]    # This is the trigger, we set 'push' as our trigger, each time we push codes to github, it automatically runs the jobs to change or checks.

#defining a specific jobs
jobs:
  test-lint:      # it is a job name or job_id
    name: Test and Lint
    runs-on: ubuntu-20.04   # it is the runner or operating system which runs the job
    steps:
      # it is used to log in to docker with the following credentials, N.B.: We have previously set up "DOCKERHUB_USER" & "DOCKERHUB_TOKEN" as the secret token in our github project.
      - name: Login to Docker Hub
        uses: docker/login-action@v1  
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # after log in, it will perform the checkout
      - name: Checkout
        uses: actions/checkout@v2

      # to perform our custom checks, se set it to run our test.py file
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"
      
      # to implement the flake8 file for linting purpose
      - name: Lint   
        run: docker compose run --rm app sh -c "flake8"
